name: Feature Request
description: Suggest a new feature or enhancement for the SDK
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We value community input in shaping the SDK's roadmap.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve? What use case does this address?
      placeholder: I want to deploy sites to multiple IPFS gateways simultaneously, but currently...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Add a new method `sdk.sites().deployToMultipleGateways()` that accepts an array of gateway URLs...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design (Optional)
      description: What should the API look like?
      render: typescript
      placeholder: |
        const deployment = await sdk.sites().deployToMultipleGateways({
          siteId: 'site-123',
          gateways: [
            'https://ipfs.io',
            'https://dweb.link',
            'https://my-custom-gateway.com'
          ]
        });
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: I could manually loop through gateways, but that's inefficient...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Would you be willing to contribute?
      description: Are you willing to submit a PR for this feature?
      options:
        - "Yes, I can submit a PR"
        - "Yes, with guidance"
        - "No, but I can help test"
        - "No"
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        I'm building a censorship-resistant news platform that needs to ensure content is available across multiple gateways...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Here's how another SDK handles this...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and discussions to ensure this hasn't been requested
          required: true
        - label: This feature aligns with the project's goals (privacy, censorship resistance, decentralization)
          required: true
        - label: I have considered how this feature might affect existing users
          required: false
