name: Security Vulnerability
description: Report a security vulnerability (PLEASE READ CAREFULLY)
title: "[SECURITY]: "
labels: ["security"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **STOP! Please read this carefully before proceeding.**

        ## For Security Vulnerabilities

        **DO NOT** submit security vulnerabilities as public GitHub issues!

        Instead, please report them privately to: **security@alternatefutures.ai**

        We will:
        - Respond within 48 hours
        - Work with you to understand and fix the issue
        - Coordinate responsible disclosure
        - Credit you (if desired) once the fix is deployed

        ## This Form is for Non-Security Issues

        If you're not reporting a security vulnerability, please use one of these instead:
        - **Bug Report**: For bugs that don't have security implications
        - **Feature Request**: For suggesting new features

        ---

        Only proceed if you're reporting a **general security concern** (not a vulnerability).
        Examples:
        - Suggesting security improvements
        - Questions about security best practices
        - Documentation improvements for security features

  - type: dropdown
    id: type
    attributes:
      label: Is this a vulnerability report?
      description: Please be honest - we need to handle vulnerabilities privately
      options:
        - "No, this is a general security concern or suggestion"
        - "Yes, this is a vulnerability (I will email security@alternatefutures.ai instead)"
    validations:
      required: true

  - type: textarea
    id: concern
    attributes:
      label: Security Concern
      description: Describe your security concern or suggestion
      placeholder: |
        I noticed that the documentation doesn't mention rate limiting for API calls...
        I suggest adding guidance on secure token storage...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of security concern is this?
      options:
        - Documentation improvement
        - Best practice suggestion
        - Security feature request
        - Question about security
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: Who might be affected by this concern?
      placeholder: SDK users who don't follow security best practices might...
    validations:
      required: false

  - type: textarea
    id: recommendation
    attributes:
      label: Recommendation
      description: What do you suggest we do?
      placeholder: |
        Add a section in SECURITY.md about...
        Implement a warning when...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I confirm this is NOT a security vulnerability (vulnerabilities should be emailed to security@alternatefutures.ai)
          required: true
        - label: I have read the SECURITY.md file
          required: false
